config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root 'static_pages#index'
 resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bishop.rb
class Bishop < Piece

end

app/models/game.rb
class Game < ApplicationRecord
	belongs_to :user
	has_many :pieces
end

app/models/king.rb
class King < Piece

end

app/models/knight.rb
class Knight < Piece

end

app/models/move.rb
class Move < ApplicationRecord

end

app/models/pawn.rb
class Pawn < Piece

end

app/models/piece.rb
class Piece < ApplicationRecord
belongs_to :game
end

app/models/queen.rb
class Queen < Piece

end

app/models/rook.rb
class Rook < Piece

end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
before_action :authenticate_user!

def new
	@game = Game.new
end
def create
@game = current_user.games.create(game_params)
redirect_to game_path(@game)
	end
def show
	@game = Game.find(params[:id])

end

def game_params
params.require(:game).permit(:name, :user_id)
	end

end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
def index
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/games/new.html.erb
<h2> Create Game </h2>
<%= simple_form_for @game do |f| %>
<div class="input">
    <%= f.input :name %>
</div>
<%= f.submit "Create!", class: 'btn btn-success' %>
<% end %>

app/views/games/show.html.erb
<h1> It's a game right here</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>HorrellChess</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a routerLink="/" class="navbar-brand" href="/">Yermuv</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/games/new">Create Game</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/games/:id">Games</a>
            </li>
            <li class="nav-item">
        </ul>
        <ul class="navbar-nav">
            <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <% end %>
        </ul>
    </nav>
    <% if notice.present? %>
    <p class="alert alert-info">
        <%= notice %>
    </p>
    <% end %>
    <% if alert.present? %>
    <p class="alert alert-danger">
        <%= alert %>
    </p>
    <% end %>
    <%= yield %>
</body>

</html>

app/views/static_pages/index.html.erb
<h1> Welcome</h1>
<h2>
    <%= link_to 'Go to Game', new_game_path, class: "btn btn-success"  %>
</h2>